development:  &default_settings
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: contacts_development
  username: root
  password: leopard01
  socket: /tmp/mysql.sock
  pool: 5
  
test:
  <<: *default_settings
  database: contacts_test
  
staging:
  <<: *default_settings
  database: contacts_staging
  
production:
  <<: *default_settings
  database: contacts_production
