development: &non_production_settings
  site_url: http://localhost:3000
  site_name: WOMEN Unlimited CRM
  admin_email: dclemente@iquantum.com
  
test:
  <<: *non_production_settings

staging:
  <<: *non_production_settings
  site_url: http://crm.women-unlimited.com
  
production:
  <<: *non_production_settings
  site_url: http://crm.women-unlimited.com
